In [2]:
import numpy as np

In [3]:
X1 = np.ones((5,2))
print(X1)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [4]:
X2 = np.ones((5,2))
X2 *= 4

In [5]:
print(X2)

[[4. 4.]
 [4. 4.]
 [4. 4.]
 [4. 4.]
 [4. 4.]]


In [18]:
X3 = X1[0, :] - X2
print(X3)
X3 = np.linalg.norm(X3, axis=1)
print(X3)

[[-4 -1]
 [-5 -6]
 [-2 -2]
 [-3 -1]
 [-1 -1]]
[4.12310563 7.81024968 2.82842712 3.16227766 1.41421356]


In [10]:
X1 = np.arange(10).reshape((5,2))
print(X1)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [13]:
X2 = np.array([4,2,5,7,2,3,3,2,1,2]).reshape((5,2))
print(X2)

[[4 2]
 [5 7]
 [2 3]
 [3 2]
 [1 2]]


In [1]:
import os
import pickle
import argparse
import matplotlib.pyplot as plt
import numpy as np
from numpy.linalg import norm
from sklearn.model_selection import train_test_split

import utils
import logReg
from logReg import logRegL2, kernelLogRegL2, kernel_poly
from pca import PCA, AlternativePCA, RobustPCA
def load_dataset(filename):
    with open(os.path.join("..", "data", filename), "rb") as f:
        return pickle.load(f)



In [ ]:
dataset = load_dataset("nonLinearData.pkl")
X = dataset["X"]
y = dataset["y"]

Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, random_state=0)

# YOUR CODE HERE
for sigma in range(-2, 3):
    for lammy in range(-4, 1):
        model = kernelLogRegL2(lammy=lammy, sigma=sigma)
        model.fit(Xtrain, ytrain)
        print(f'Sigma: {sigma} lambda: {lammy}')
        print(
            "Training error RBFs Kernel %.3f"
            % np.mean(model.predict(Xtrain) != ytrain)
        )
        print(
            "Validation error RBFs Kernel %.3f"
            % np.mean(model.predict(Xtest) != ytest)
        )



100%|██████████| 300/300 [00:00<00:00, 20665.33it/s]
/Users/kaisawamoto/Desktop/CPSC/cpsc340/a5/code/logReg.py:84: RuntimeWarning: overflow encountered in exp
  f = np.sum(np.log(1.0 + np.exp(-yKu)))
/Users/kaisawamoto/Desktop/CPSC/cpsc340/a5/code/logReg.py:11: RuntimeWarning: overflow encountered in exp
  out = np.log(1 + np.exp(x))
/Users/kaisawamoto/Desktop/CPSC/cpsc340/a5/code/logReg.py:91: RuntimeWarning: overflow encountered in exp
  res = -y / (1.0 + np.exp(yKu))
/Users/kaisawamoto/Desktop/CPSC/cpsc340/a5/code/logReg.py:88: RuntimeWarning: overflow encountered in matmul
  f += 0.5 * self.lammy * u.T @ K @ u
/Users/kaisawamoto/Desktop/CPSC/cpsc340/a5/code/findMin.py:45: RuntimeWarning: invalid value encountered in double_scalars
  alpha = -alpha*np.dot(y.T,g) / np.dot(y.T,y)
100%|██████████| 300/300 [00:00<00:00, 23633.43it/s]


Training error RBFs Kernel 0.380
Validation error RBFs Kernel 0.360
Training error RBFs Kernel 0.380
Validation error RBFs Kernel 0.360


100%|██████████| 300/300 [00:00<00:00, 24915.18it/s]


Training error RBFs Kernel 0.380
Validation error RBFs Kernel 0.360
Training error RBFs Kernel 0.380
Validation error RBFs Kernel 0.360


100%|██████████| 300/300 [00:00<00:00, 21940.56it/s]


Training error RBFs Kernel 0.140
Validation error RBFs Kernel 0.130
Training error RBFs Kernel 0.380
Validation error RBFs Kernel 0.360


100%|██████████| 300/300 [00:00<00:00, 21528.76it/s]


Training error RBFs Kernel 0.380
Validation error RBFs Kernel 0.360
Training error RBFs Kernel 0.380
Validation error RBFs Kernel 0.360


  0%|          | 0/300 [00:00<?, ?it/s]/Users/kaisawamoto/Desktop/CPSC/cpsc340/a5/code/logReg.py:58: RuntimeWarning: divide by zero encountered in true_divide
  K[i1, :] = np.exp(-(np.linalg.norm(X1[i1, :] - X2, axis=1) / (2 * sigma ** 2)))
/Users/kaisawamoto/Desktop/CPSC/cpsc340/a5/code/logReg.py:58: RuntimeWarning: invalid value encountered in true_divide
  K[i1, :] = np.exp(-(np.linalg.norm(X1[i1, :] - X2, axis=1) / (2 * sigma ** 2)))
100%|██████████| 300/300 [00:00<00:00, 21346.51it/s]
/Users/kaisawamoto/Desktop/CPSC/cpsc340/a5/code/logReg.py:12: RuntimeWarning: invalid value encountered in greater
  out[x > 100] = x[x > 100]
/Users/kaisawamoto/Desktop/CPSC/cpsc340/a5/code/logReg.py:13: RuntimeWarning: invalid value encountered in less
  out[x < -100] = np.exp(x[x < -100])


Training error RBFs Kernel 0.380
Validation error RBFs Kernel 0.360
Training error RBFs Kernel 0.130
Validation error RBFs Kernel 0.110


/Users/kaisawamoto/Desktop/CPSC/cpsc340/a5/code/utils.py:56: RuntimeWarning: invalid value encountered in greater
  if np.max(np.abs(estimated_gradient - implemented_gradient) > 1e-3):
